name: "Test template"
description: "Install, lint, typecheck and test a FastAPI app"
inputs:
  workdir:
    description: "Working directory to run tests in"
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ inputs.workdir }}
        uv venv --python $(which python)
        source .venv/bin/activate

        uv pip install -e .[dev]

        cp .env.example .env
        
        echo "Running Ruff..."
        ruff check app tests

        echo "Running MyPy..."
        mypy app

        echo "Running Pytest..."
        pytest

      shell: bash