exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",       
    "venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
]

line-length = 88

target-version = "py313"

[lint]
# E = pycodestyle errors
# F = Pyflakes
# W = pycodestyle Warnings
# I = isort
select = ["E", "F", "W", "I"]

[format]