name: CI Checks

on:
  pull_request:
    branches: [ main, next, develop ]

  workflow_dispatch:

jobs:
  lint:
    name: Linting & Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Dependencies
        run: |
          uv venv .venv --python 3.13
          source .venv/bin/activate
          uv pip install -e .[dev]

      - name: Lint
        run: source .venv/bin/activate && ruff check app tests

      - name: Check types
        run: source .venv/bin/activate && mypy app

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Dependencies
        run: |
          uv venv .venv --python 3.13
          source .venv/bin/activate
          uv pip install -e .[dev]


      - name: Run Pytest
        run: source .venv/bin/activate && pytest
