name: Check linting

on:
  pull_request:
    branches: [develop, next, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install ruff mypy

      - name: Run ruff
        run: ruff check app
        if: always()
      
      - name: Run mypy
        run: mypy app
        if: always()
